  - name: ping - lets see we are ok
    ping:

  - name: verify java is installed
    yum: name=java-1.8.0-openjdk state=present
  
  - name: verify python is installed 
    yum: name=python state=present

  - name: Add Cassandra repository
    yum_repository:
      name: cassandra
      description: DataStax Repo for Apache Cassandra
      baseurl: http://rpm.datastax.com/community
      enabled: 1
      gpgcheck: 0

  - name: verify Cassandra is installed
    yum: name=dsc20 state=present

  - name: force systemd to reread configs (2.4 and above)
    systemd: daemon_reload=yes
 
  # set the seed in the cassandra.yaml file, before starting the service, for all servers in the cassandra cluster
  - lineinfile:
      path: /etc/cassandra/conf/cassandra.yaml
      regexp: '- seeds:'
      line: "          - seeds: {{hostvars['cseed01']['ansible_ssh_host']}}"
                    
  # set endpoint_snitch: Ec2Snitch , for all servers in the cassandra cluster
  - lineinfile:
      path: /etc/cassandra/conf/cassandra.yaml
      regexp: 'endpoint_snitch:'
      line: "endpoint_snitch: Ec2Snitch"
