va_version: 8u161
download_url: "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-{{java_version}}-linux-x64.tar.gz"
download_folder: /opt
java_name: "{{download_folder}}/jdk{{java_version}}"
java_archive: "{{download_folder}}/jdk-{{java_version}}-linux-x64.tar.gz"
